apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: app-name
    literals:
      - APP_NAME=darts
#      - PG_USER=darts_admin_user
#      - PG_DATABASE=darts_db
#      - PG_RW_USER=darts_rw_user
#      - PG_RO_USER=darts_ro_user
  - name: cluster-prefix
    literals:
      - CLUSTER_PREFIX="sipr-mission-prod"

components:
  - app-db-creds/
  - minio-creds/
  - mongo-creds/
  - darts-secrets/
