apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

labels:
- includeSelectors: true
  pairs:
    micro-svc: rabbitmq
- pairs:
    app-type: ironbank


generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - rabbitmq.conf
  name: rabbitmq-config-cm
