apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pv-storage
  labels:
    micro-svc: rabbitmq
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"