apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline    
  logstash.conf: |
    input {
      kafka{
        codec => json
        bootstrap_servers => "kafka:9092"
        topics => ["custom-logging"]
      }
    }
    
    filter {
    }
    
    output {
      stdout {
            codec => json_lines
        }
      elasticsearch {
          hosts => ["elasticsearch:9200"]
          index => "sewol-log"
      }
    }

