kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   labels:
      app: logstash
   name: logstash
spec:
   accessModes:
      - "ReadWriteOnce"
   resources:
      requests:
         storage: "1Gi"
