GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA <APP>_schema TO <APP>_rw_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA <APP>_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO <APP>_rw_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA <APP>_schema GRANT USAGE, SELECT ON SEQUENCES TO <APP>_rw_user;
