apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Comment-out when using sops
generatorOptions:
  disableNameSuffixHash: true

# Comment-out when using sops
secretGenerator:
  - name: minio-app-keys
    envs:
    - darts-minio-creds.env
    type: Opaque

# Uncomment when using sops
#generators:
#  - minio-creds-generator.yaml