apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  template:
    spec:
      imagePullSecrets:
      - name: code-il5-pull-creds
      containers:
      - name: kafka
        image: registry1.dso.mil/ironbank/bitnami/kafka:3.4.0
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CREATE_TOPICS
          value: test-1
        ports:
          - containerPort: 9092
        resources:
          limits:
            cpu: 4000m
            memory: 6Gi
          requests:
            cpu: 1000m
            memory: 2Gi
