apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  ports:
  - protocol: TCP
    port: 61616
    targetPort: 61616
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-console
spec:
  selector:
    app: activemq
  ports:
    - protocol: TCP
      port: 8161
      targetPort: 8161
