apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml
- pvc.yaml

labels:
- includeSelectors: true
  pairs:
    app: elasticsearch
- pairs:
    appType: ironbank
