apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
spec:
  revisionHistoryLimit: 1
  template:
    spec:
      terminationGracePeriodSeconds: 15
      imagePullSecrets:
      - name: code-il5-pull-creds
      containers:
      - name: data-service
        image: sewol/data-service
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
        volumeMounts:
        - name: ephemeral
          mountPath: /tmp
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 5
        env:
        - name: LOG_LEVEL
          value: INFO
        - name: SUBSYSTEM
          value: Dataservice 
        - name: KAFKA_HOST
          value: kafka.sewol.svc.cluster.local:9092
        envFrom:
        - secretRef:
            name: app-db-credentials
        - secretRef:
            name: postgres-connect-info
        - configMapRef:
            name: app-name
      volumes:
      - name: ephemeral
        emptyDir: {}
