apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedestal-api
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/userVolumeMount: '[{"name":"certs", "mountPath":"/certs/tls.crt", "readonly":true, "subPath":"tls.crt"},{"name":"certs", "mountPath":"/certs/tls.key", "readonly":true, "subPath":"tls.key"},{"name":"certs", "mountPath":"/certs/ca.crt", "readonly":true, "subPath":"ca.crt"}]'
        sidecar.istio.io/userVolume: '[{"name":"certs", "secret":{"secretName":"mtls-certs"}}]'
    spec:
      containers:
      - name: pedestal-api
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: minio-app-keys
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: minio-app-keys
        - name: S3_BUCKET_UUID
          valueFrom:
            secretKeyRef:
              key: appS3BucketUUID
              name: minio-app-keys
        - name: MINIO_ENDPOINT_URL
          value: http://minio.minio.svc.cluster.local:9000
        - name: MINIO_BUCKET_NAME
          value: minio-$(NAMESPACE)-$(CLUSTER_PREFIX)-$(S3_BUCKET_UUID)
        - name: MINIO_S3_BUCKET
          value: $(MINIO_BUCKET_NAME)
        - name: FILESTORE_URL
          value: $(MINIO_ENDPOINT_URL)
        - name: DOCUMENT_QUEUE_NAME
          value: pedestal_documents
        - name: PEDESTAL_ADMINS
          value: juve,williamstp
        - name: CLAMAV_HOST
          value: clamd.clamav
        - name: CLAMAV_PORT
          value: "3310"
