apiVersion: apps/v1
kind: Deployment
metadata:
  name: defaults
spec:
  revisionHistoryLimit: 1
  template:
    spec:
      terminationGracePeriodSeconds: 15
      #imagePullSecrets:
      #- name: code-il4-pull-creds
