namespace: tiger-ranch-training-db

resources:
  - ../../../../base/resources/tiger-ranch-db/

configMapGenerator:
  - name: app-name
    behavior: merge
    literals:
      - APP_NAME=tiger-ranch-training

components:
  - ../../../../../cluster-configmaps/prod/
  - ../secrets/

patchesStrategicMerge:
  - ./patches/auth-policy-patch.yaml

patches:
  - path: ./patches/namespace-patch.yaml
    target:
      version: v1
      kind: Namespace
      name: tiger-ranch-training-db

