apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: coi-rmt-simulator
  authentication: istio-auth

resources:
- deployment.yaml
- service.yaml


resources:
- deployment.yaml
- service.yaml

patches:
 - target:
      group: apps
      version: v1
      kind: Deployment
      name: coi-rmt-simulator
   path: probe-patch.json


