apiVersion: apps/v1
kind: Deployment
metadata:
  name: coi-rmt-communication
spec:
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  template:
    spec:
      terminationGracePeriodSeconds: 15
      imagePullSecrets:
        - name: code-il5-pull-creds
      containers:
        - name: coi-rmt-communication
          image: sewol/coi-rmt-communication
          imagePullPolicy: Always
          resources:
            limits:
              memory: 2.5Gi
            requests:
              memory: 2.5Gi
          volumeMounts:
            - name: ephemeral
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 5
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: KAFKA_HOST
              value: kafka.sewol.svc.cluster.local:9092
            - name: SUBSYSTEM
              value: CoiResource
      volumes:
        - name: ephemeral
          emptyDir: {}
